//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace EsealUpdate.com.rahmat_faisal.www {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiceSoap", Namespace="http://tempuri.org/")]
    public partial class Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
        
        private System.Threading.SendOrPostCallback Retrive_Image_NameOperationCompleted;
        
        private System.Threading.SendOrPostCallback Retrive_ImageOperationCompleted;
        
        private System.Threading.SendOrPostCallback updateImagedataOperationCompleted;
        
        private System.Threading.SendOrPostCallback G_NamaKaryawanOperationCompleted;
        
        private System.Threading.SendOrPostCallback CheckEmployeeIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback G_JamPhotoOperationCompleted;
        
        private System.Threading.SendOrPostCallback G_EmployeeIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback G_ListAbsensiOperationCompleted;
        
        private System.Threading.SendOrPostCallback G_esealOperationCompleted;
        
        private System.Threading.SendOrPostCallback G_IMEIOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service() {
            this.Url = "http://www.rahmat-faisal.com/service.asmx";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event HelloWorldCompletedEventHandler HelloWorldCompleted;
        
        /// <remarks/>
        public event Retrive_Image_NameCompletedEventHandler Retrive_Image_NameCompleted;
        
        /// <remarks/>
        public event Retrive_ImageCompletedEventHandler Retrive_ImageCompleted;
        
        /// <remarks/>
        public event updateImagedataCompletedEventHandler updateImagedataCompleted;
        
        /// <remarks/>
        public event G_NamaKaryawanCompletedEventHandler G_NamaKaryawanCompleted;
        
        /// <remarks/>
        public event CheckEmployeeIDCompletedEventHandler CheckEmployeeIDCompleted;
        
        /// <remarks/>
        public event G_JamPhotoCompletedEventHandler G_JamPhotoCompleted;
        
        /// <remarks/>
        public event G_EmployeeIDCompletedEventHandler G_EmployeeIDCompleted;
        
        /// <remarks/>
        public event G_ListAbsensiCompletedEventHandler G_ListAbsensiCompleted;
        
        /// <remarks/>
        public event G_esealCompletedEventHandler G_esealCompleted;
        
        /// <remarks/>
        public event G_IMEICompletedEventHandler G_IMEICompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWorld", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        /// <remarks/>
        public void HelloWorldAsync(object userState) {
            if ((this.HelloWorldOperationCompleted == null)) {
                this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
            }
            this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
        }
        
        private void OnHelloWorldOperationCompleted(object arg) {
            if ((this.HelloWorldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Retrive_Image_Name", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet Retrive_Image_Name() {
            object[] results = this.Invoke("Retrive_Image_Name", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void Retrive_Image_NameAsync() {
            this.Retrive_Image_NameAsync(null);
        }
        
        /// <remarks/>
        public void Retrive_Image_NameAsync(object userState) {
            if ((this.Retrive_Image_NameOperationCompleted == null)) {
                this.Retrive_Image_NameOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRetrive_Image_NameOperationCompleted);
            }
            this.InvokeAsync("Retrive_Image_Name", new object[0], this.Retrive_Image_NameOperationCompleted, userState);
        }
        
        private void OnRetrive_Image_NameOperationCompleted(object arg) {
            if ((this.Retrive_Image_NameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Retrive_Image_NameCompleted(this, new Retrive_Image_NameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Retrive_Image", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] Retrive_Image(string nip, string jenisabsen, System.DateTime inputdate) {
            object[] results = this.Invoke("Retrive_Image", new object[] {
                        nip,
                        jenisabsen,
                        inputdate});
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public void Retrive_ImageAsync(string nip, string jenisabsen, System.DateTime inputdate) {
            this.Retrive_ImageAsync(nip, jenisabsen, inputdate, null);
        }
        
        /// <remarks/>
        public void Retrive_ImageAsync(string nip, string jenisabsen, System.DateTime inputdate, object userState) {
            if ((this.Retrive_ImageOperationCompleted == null)) {
                this.Retrive_ImageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRetrive_ImageOperationCompleted);
            }
            this.InvokeAsync("Retrive_Image", new object[] {
                        nip,
                        jenisabsen,
                        inputdate}, this.Retrive_ImageOperationCompleted, userState);
        }
        
        private void OnRetrive_ImageOperationCompleted(object arg) {
            if ((this.Retrive_ImageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Retrive_ImageCompleted(this, new Retrive_ImageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/updateImagedata", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void updateImagedata(string nip, string jenisabsen, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] data) {
            this.Invoke("updateImagedata", new object[] {
                        nip,
                        jenisabsen,
                        data});
        }
        
        /// <remarks/>
        public void updateImagedataAsync(string nip, string jenisabsen, byte[] data) {
            this.updateImagedataAsync(nip, jenisabsen, data, null);
        }
        
        /// <remarks/>
        public void updateImagedataAsync(string nip, string jenisabsen, byte[] data, object userState) {
            if ((this.updateImagedataOperationCompleted == null)) {
                this.updateImagedataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnupdateImagedataOperationCompleted);
            }
            this.InvokeAsync("updateImagedata", new object[] {
                        nip,
                        jenisabsen,
                        data}, this.updateImagedataOperationCompleted, userState);
        }
        
        private void OnupdateImagedataOperationCompleted(object arg) {
            if ((this.updateImagedataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.updateImagedataCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/G_NamaKaryawan", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string G_NamaKaryawan(string nip) {
            object[] results = this.Invoke("G_NamaKaryawan", new object[] {
                        nip});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void G_NamaKaryawanAsync(string nip) {
            this.G_NamaKaryawanAsync(nip, null);
        }
        
        /// <remarks/>
        public void G_NamaKaryawanAsync(string nip, object userState) {
            if ((this.G_NamaKaryawanOperationCompleted == null)) {
                this.G_NamaKaryawanOperationCompleted = new System.Threading.SendOrPostCallback(this.OnG_NamaKaryawanOperationCompleted);
            }
            this.InvokeAsync("G_NamaKaryawan", new object[] {
                        nip}, this.G_NamaKaryawanOperationCompleted, userState);
        }
        
        private void OnG_NamaKaryawanOperationCompleted(object arg) {
            if ((this.G_NamaKaryawanCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.G_NamaKaryawanCompleted(this, new G_NamaKaryawanCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CheckEmployeeID", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CheckEmployeeID(string nip, string pwd) {
            object[] results = this.Invoke("CheckEmployeeID", new object[] {
                        nip,
                        pwd});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CheckEmployeeIDAsync(string nip, string pwd) {
            this.CheckEmployeeIDAsync(nip, pwd, null);
        }
        
        /// <remarks/>
        public void CheckEmployeeIDAsync(string nip, string pwd, object userState) {
            if ((this.CheckEmployeeIDOperationCompleted == null)) {
                this.CheckEmployeeIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheckEmployeeIDOperationCompleted);
            }
            this.InvokeAsync("CheckEmployeeID", new object[] {
                        nip,
                        pwd}, this.CheckEmployeeIDOperationCompleted, userState);
        }
        
        private void OnCheckEmployeeIDOperationCompleted(object arg) {
            if ((this.CheckEmployeeIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CheckEmployeeIDCompleted(this, new CheckEmployeeIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/G_JamPhoto", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.DateTime G_JamPhoto(string nip, string jenisabs) {
            object[] results = this.Invoke("G_JamPhoto", new object[] {
                        nip,
                        jenisabs});
            return ((System.DateTime)(results[0]));
        }
        
        /// <remarks/>
        public void G_JamPhotoAsync(string nip, string jenisabs) {
            this.G_JamPhotoAsync(nip, jenisabs, null);
        }
        
        /// <remarks/>
        public void G_JamPhotoAsync(string nip, string jenisabs, object userState) {
            if ((this.G_JamPhotoOperationCompleted == null)) {
                this.G_JamPhotoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnG_JamPhotoOperationCompleted);
            }
            this.InvokeAsync("G_JamPhoto", new object[] {
                        nip,
                        jenisabs}, this.G_JamPhotoOperationCompleted, userState);
        }
        
        private void OnG_JamPhotoOperationCompleted(object arg) {
            if ((this.G_JamPhotoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.G_JamPhotoCompleted(this, new G_JamPhotoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/G_EmployeeID", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string G_EmployeeID(string MobileNo) {
            object[] results = this.Invoke("G_EmployeeID", new object[] {
                        MobileNo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void G_EmployeeIDAsync(string MobileNo) {
            this.G_EmployeeIDAsync(MobileNo, null);
        }
        
        /// <remarks/>
        public void G_EmployeeIDAsync(string MobileNo, object userState) {
            if ((this.G_EmployeeIDOperationCompleted == null)) {
                this.G_EmployeeIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnG_EmployeeIDOperationCompleted);
            }
            this.InvokeAsync("G_EmployeeID", new object[] {
                        MobileNo}, this.G_EmployeeIDOperationCompleted, userState);
        }
        
        private void OnG_EmployeeIDOperationCompleted(object arg) {
            if ((this.G_EmployeeIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.G_EmployeeIDCompleted(this, new G_EmployeeIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/G_ListAbsensi", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet G_ListAbsensi(string nip, int bulan, int tahun) {
            object[] results = this.Invoke("G_ListAbsensi", new object[] {
                        nip,
                        bulan,
                        tahun});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void G_ListAbsensiAsync(string nip, int bulan, int tahun) {
            this.G_ListAbsensiAsync(nip, bulan, tahun, null);
        }
        
        /// <remarks/>
        public void G_ListAbsensiAsync(string nip, int bulan, int tahun, object userState) {
            if ((this.G_ListAbsensiOperationCompleted == null)) {
                this.G_ListAbsensiOperationCompleted = new System.Threading.SendOrPostCallback(this.OnG_ListAbsensiOperationCompleted);
            }
            this.InvokeAsync("G_ListAbsensi", new object[] {
                        nip,
                        bulan,
                        tahun}, this.G_ListAbsensiOperationCompleted, userState);
        }
        
        private void OnG_ListAbsensiOperationCompleted(object arg) {
            if ((this.G_ListAbsensiCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.G_ListAbsensiCompleted(this, new G_ListAbsensiCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/G_eseal", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet G_eseal() {
            object[] results = this.Invoke("G_eseal", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void G_esealAsync() {
            this.G_esealAsync(null);
        }
        
        /// <remarks/>
        public void G_esealAsync(object userState) {
            if ((this.G_esealOperationCompleted == null)) {
                this.G_esealOperationCompleted = new System.Threading.SendOrPostCallback(this.OnG_esealOperationCompleted);
            }
            this.InvokeAsync("G_eseal", new object[0], this.G_esealOperationCompleted, userState);
        }
        
        private void OnG_esealOperationCompleted(object arg) {
            if ((this.G_esealCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.G_esealCompleted(this, new G_esealCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/G_IMEI", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string G_IMEI(string esealno) {
            object[] results = this.Invoke("G_IMEI", new object[] {
                        esealno});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void G_IMEIAsync(string esealno) {
            this.G_IMEIAsync(esealno, null);
        }
        
        /// <remarks/>
        public void G_IMEIAsync(string esealno, object userState) {
            if ((this.G_IMEIOperationCompleted == null)) {
                this.G_IMEIOperationCompleted = new System.Threading.SendOrPostCallback(this.OnG_IMEIOperationCompleted);
            }
            this.InvokeAsync("G_IMEI", new object[] {
                        esealno}, this.G_IMEIOperationCompleted, userState);
        }
        
        private void OnG_IMEIOperationCompleted(object arg) {
            if ((this.G_IMEICompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.G_IMEICompleted(this, new G_IMEICompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void Retrive_Image_NameCompletedEventHandler(object sender, Retrive_Image_NameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Retrive_Image_NameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Retrive_Image_NameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void Retrive_ImageCompletedEventHandler(object sender, Retrive_ImageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Retrive_ImageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Retrive_ImageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public byte[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void updateImagedataCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void G_NamaKaryawanCompletedEventHandler(object sender, G_NamaKaryawanCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class G_NamaKaryawanCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal G_NamaKaryawanCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void CheckEmployeeIDCompletedEventHandler(object sender, CheckEmployeeIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CheckEmployeeIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CheckEmployeeIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void G_JamPhotoCompletedEventHandler(object sender, G_JamPhotoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class G_JamPhotoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal G_JamPhotoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.DateTime Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.DateTime)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void G_EmployeeIDCompletedEventHandler(object sender, G_EmployeeIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class G_EmployeeIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal G_EmployeeIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void G_ListAbsensiCompletedEventHandler(object sender, G_ListAbsensiCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class G_ListAbsensiCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal G_ListAbsensiCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void G_esealCompletedEventHandler(object sender, G_esealCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class G_esealCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal G_esealCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void G_IMEICompletedEventHandler(object sender, G_IMEICompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class G_IMEICompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal G_IMEICompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591