#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("EsealUpdate.Resource", IsApplication=true)]

namespace EsealUpdate
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.ApplicationName = global::EsealUpdate.Resource.String.ApplicationName;
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.Hello = global::EsealUpdate.Resource.String.Hello;
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050000
			public const int Geseal_array = 2131034112;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Agility = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int bg_agility = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Notification = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060006
			public const int AutoCompleteInput = 2131099654;
			
			// aapt resource value: 0x7f060004
			public const int BtnLogin = 2131099652;
			
			// aapt resource value: 0x7f06001c
			public const int Btn_Add = 2131099676;
			
			// aapt resource value: 0x7f06001b
			public const int Btn_Submit = 2131099675;
			
			// aapt resource value: 0x7f060009
			public const int ShipmentID = 2131099657;
			
			// aapt resource value: 0x7f060007
			public const int etIMEI = 2131099655;
			
			// aapt resource value: 0x7f060005
			public const int geseal = 2131099653;
			
			// aapt resource value: 0x7f060003
			public const int password = 2131099651;
			
			// aapt resource value: 0x7f060008
			public const int spinner = 2131099656;
			
			// aapt resource value: 0x7f060000
			public const int textView1 = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int textView2 = 2131099650;
			
			// aapt resource value: 0x7f06000a
			public const int textview1 = 2131099658;
			
			// aapt resource value: 0x7f06001a
			public const int tgl_date = 2131099674;
			
			// aapt resource value: 0x7f060013
			public const int txAju = 2131099667;
			
			// aapt resource value: 0x7f060017
			public const int txCont = 2131099671;
			
			// aapt resource value: 0x7f06000e
			public const int txDo = 2131099662;
			
			// aapt resource value: 0x7f060010
			public const int txJob = 2131099664;
			
			// aapt resource value: 0x7f060015
			public const int txPcUp = 2131099669;
			
			// aapt resource value: 0x7f06000c
			public const int txSopir = 2131099660;
			
			// aapt resource value: 0x7f060019
			public const int txTgl = 2131099673;
			
			// aapt resource value: 0x7f06000d
			public const int txt_NamaSopir = 2131099661;
			
			// aapt resource value: 0x7f060014
			public const int txt_NoAju = 2131099668;
			
			// aapt resource value: 0x7f06000f
			public const int txt_NoDO = 2131099663;
			
			// aapt resource value: 0x7f060011
			public const int txt_NoDo = 2131099665;
			
			// aapt resource value: 0x7f060012
			public const int txt_NoJob = 2131099666;
			
			// aapt resource value: 0x7f06000b
			public const int txt_NoMobil = 2131099659;
			
			// aapt resource value: 0x7f060016
			public const int txt_PickUpDari = 2131099670;
			
			// aapt resource value: 0x7f060018
			public const int txt_noContainer = 2131099672;
			
			// aapt resource value: 0x7f060001
			public const int userName = 2131099649;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int list_item = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Login = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Update = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int app_name = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int planet_prompt = 2130968579;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
